export type EvidenceLevel = "S" | "A" | "C";

export type SourceCategory =
  | "本人文章 / 信件"
  | "投资者沟通"
  | "公司活动"
  | "产品发布"
  | "采访"
  | "监管与法律"
  | "测试 / 行动记录"
  | "公司公告"
  | "学术发表";

export type Organization =
  | "Tesla"
  | "SpaceX"
  | "Neuralink"
  | "xAI"
  | "X"
  | "媒体采访"
  | "监管 / 法院";

export type MuskRole =
  | "本人完整发言"
  | "本人参与问答"
  | "本人署名文本"
  | "公司 / 监管行动记录";

export type SourceFormat =
  | "完整视频"
  | "完整音频 / 回放"
  | "完整文字稿"
  | "视频片段 / 节录"
  | "官方网页 / 文章"
  | "官方 PDF / 法律文件"
  | "学术论文";

export type SourceAccess = "稳定直达" | "可能受地区 / 平台限制" | "需人工复核";

export type EvidenceSource = {
  id: string;
  title: string;
  date: string;
  publishedAt?: string;
  category: SourceCategory;
  organization: Organization;
  publisher: string;
  official: boolean;
  muskRole: MuskRole;
  sourceFormat: SourceFormat;
  completeness: "完整视频" | "完整音频 / 回放" | "完整文字稿" | "官方摘录 / 公告" | "行动记录" | "待人工核验";
  evidenceLevel: EvidenceLevel;
  access: SourceAccess;
  primaryUrl: string;
  archiveUrl?: string;
  supplementaryUrl?: string;
  supplementaryLabel?: string;
  context: string;
  researchNote: string;
  verificationNote: string;
  tags: string[];
};

export type TimelineItem = {
  id: string;
  year: string;
  type: string;
  title: string;
  sourceId: string;
  context: string;
  observation: string;
  action: string;
  outcome: string;
  certainty: "已核验" | "需补充" | "结果待观察";
};

function teslaQuarterlyCall(id: string, date: string, quarter: string, focus: string): EvidenceSource {
  return {
    id,
    title: `Tesla ${quarter} 财报电话会与问答`,
    date,
    category: "投资者沟通",
    organization: "Tesla",
    publisher: "Tesla Investor Relations",
    official: true,
    muskRole: "本人参与问答",
    sourceFormat: "完整音频 / 回放",
    completeness: "完整音频 / 回放",
    evidenceLevel: "S",
    access: "稳定直达",
    primaryUrl: `https://ir.tesla.com/webcast-${date}`,
    context: focus,
    researchNote: "完整管理层回放，适合回看马斯克在投资者与分析师追问中的具体回答；不要把其他高管、主持人和提问者的内容归给他本人。",
    verificationNote: "Tesla IR 的单期回放入口通常无需账户。若某地区播放器不可加载，应保留这个原始地址并在后续编辑时补马斯克发言的时间码，而不是用剪辑镜像替代。",
    tags: ["Tesla", "财报", "投资者问答", "完整回放"],
  };
}

function starshipFlight(id: string, date: string, number: string, focus: string): EvidenceSource {
  return {
    id,
    title: `Starship 第${number}次飞行测试`,
    date,
    category: "测试 / 行动记录",
    organization: "SpaceX",
    publisher: "SpaceX",
    official: true,
    muskRole: "公司 / 监管行动记录",
    sourceFormat: "官方网页 / 文章",
    completeness: "行动记录",
    evidenceLevel: "S",
    access: "稳定直达",
    primaryUrl: `https://www.spacex.com/launches/starship-flight-${number}`,
    context: focus,
    researchNote: "这是 SpaceX 对测试、异常和完成目标的原始行动记录，适合与马斯克在发布会上的愿景或时间判断并列阅读。",
    verificationNote: "它不是马斯克本人逐字发言，也不能单独用来推断他的个人动机；引用时应明确它是公司公开行动记录。",
    tags: ["SpaceX", "Starship", "测试", "行动记录"],
  };
}

const teslaCalls: EvidenceSource[] = [
  teslaQuarterlyCall("tesla-q2-2018", "2018-08-01", "2018 年第二季度", "Model 3 产能、盈利、自动驾驶计算平台与跨州演示等问题进入公开问答。"),
  teslaQuarterlyCall("tesla-q3-2018", "2018-10-24", "2018 年第三季度", "Model 3 交付、盈利和制造执行压力下的公司沟通。"),
  teslaQuarterlyCall("tesla-q4-2019", "2020-01-29", "2019 年第四季度", "上海工厂、2020 年展望与产能扩张。"),
  teslaQuarterlyCall("tesla-q1-2020", "2020-04-29", "2020 年第一季度", "疫情初期的经营、工厂复工与供应链不确定性。"),
  teslaQuarterlyCall("tesla-q2-2020", "2020-07-22", "2020 年第二季度", "连续盈利、产能扩张和工厂路线。"),
  teslaQuarterlyCall("tesla-q3-2020", "2020-10-21", "2020 年第三季度", "FSD Beta 初期、产能扩张和盈利能力的同步追问。"),
  teslaQuarterlyCall("tesla-q4-2020", "2021-01-27", "2020 年第四季度", "年度收官、FSD 与工厂计划。"),
  teslaQuarterlyCall("tesla-q1-2021", "2021-04-26", "2021 年第一季度", "供应链约束、FSD 和新工厂执行。"),
  teslaQuarterlyCall("tesla-q2-2021", "2021-07-26", "2021 年第二季度", "芯片短缺、交付与产品路线。"),
  teslaQuarterlyCall("tesla-q4-2021", "2022-01-26", "2021 年第四季度", "Austin / Berlin 爬坡、FSD 与产品路线。"),
  teslaQuarterlyCall("tesla-q1-2022", "2022-04-20", "2022 年第一季度", "上海停产、工厂和供给压力。"),
  teslaQuarterlyCall("tesla-q4-2022", "2023-01-25", "2022 年第四季度", "降价、需求、年度目标与经济环境。"),
  teslaQuarterlyCall("tesla-q1-2023", "2023-04-19", "2023 年第一季度", "价格与利润取舍、FSD 与宏观环境。"),
  teslaQuarterlyCall("tesla-q3-2023", "2023-10-18", "2023 年第三季度", "Cybertruck 量产、利率、需求与经营节奏。"),
  teslaQuarterlyCall("tesla-q4-2023", "2024-01-24", "2023 年第四季度", "2024 增长、下一代平台与 AI 路线。"),
  teslaQuarterlyCall("tesla-q1-2024", "2024-04-23", "2024 年第一季度", "低价车型、Robotaxi 节奏与经营优先级。"),
  teslaQuarterlyCall("tesla-q3-2024", "2024-10-23", "2024 年第三季度", "利润、FSD / Cybercab / Optimus 和规模化表述。"),
  teslaQuarterlyCall("tesla-q1-2025", "2025-04-22", "2025 年第一季度", "经营、个人时间分配与部署问题。"),
  teslaQuarterlyCall("tesla-q2-2025", "2025-07-23", "2025 年第二季度", "Dojo、自动驾驶、产能与风险沟通。"),
  teslaQuarterlyCall("tesla-q3-2025", "2025-10-22", "2025 年第三季度", "Robotaxi、AI 算力与规模化表述。"),
  teslaQuarterlyCall("tesla-q4-2025", "2026-01-28", "2025 年第四季度", "Cybercab 生产与 2026 年目标。"),
  teslaQuarterlyCall("tesla-q1-2026", "2026-04-22", "2026 年第一季度", "最新一批公开的 Tesla 管理层问答记录。"),
];

const starshipFlights: EvidenceSource[] = [
  {
    id: "spacex-ift-1",
    title: "Starship 第 1 次飞行测试",
    date: "2023-04-20",
    category: "测试 / 行动记录",
    organization: "SpaceX",
    publisher: "SpaceX",
    official: true,
    muskRole: "公司 / 监管行动记录",
    sourceFormat: "官方网页 / 文章",
    completeness: "行动记录",
    evidenceLevel: "S",
    access: "稳定直达",
    primaryUrl: "https://www.spacex.com/launches/starship-flight-test",
    context: "首个全栈飞行测试；官方记录发动机熄火与飞行终止。",
    researchNote: "原始测试页面，可与此前的设计承诺和后续飞行测试逐项比对。",
    verificationNote: "公司测试记录，不是马斯克的个人讲话。",
    tags: ["SpaceX", "Starship", "测试", "行动记录"],
  },
  starshipFlight("spacex-ift-2", "2023-11-18", "2", "热分离成功、两级后续异常的官方记录。"),
  starshipFlight("spacex-ift-3", "2024-03-14", "3", "首次完整上升段、推进剂转移等目标与未完成事项。"),
  starshipFlight("spacex-ift-4", "2024-06-06", "4", "两级受控返回与溅落的测试记录。"),
  starshipFlight("spacex-ift-5", "2024-10-13", "5", "首次塔架捕捉 Super Heavy 的测试记录。"),
  starshipFlight("spacex-ift-6", "2024-11-19", "6", "自动健康检查后放弃捕捉、转为溅落的公开记录。"),
  starshipFlight("spacex-ift-7", "2025-01-16", "7", "助推器二次捕捉、上级失联和后续调查。"),
  starshipFlight("spacex-ift-8", "2025-03-06", "8", "捕捉成功与上级飞行异常的并存记录。"),
  starshipFlight("spacex-ift-9", "2025-05-27", "9", "首次复飞 Super Heavy 及后续异常的公开记录。"),
];

export const sources: EvidenceSource[] = [
  {
    id: "musk-master-plan-2006",
    title: "Tesla《秘密总体计划》（官方历史存档）",
    date: "2006-08-02",
    category: "本人文章 / 信件",
    organization: "Tesla",
    publisher: "Tesla / Elon Musk",
    official: true,
    muskRole: "本人署名文本",
    sourceFormat: "官方网页 / 文章",
    completeness: "完整文字稿",
    evidenceLevel: "S",
    access: "稳定直达",
    primaryUrl: "https://www.tesla.com/es_co/secret-master-plan",
    context: "早期 Tesla 战略文章，讲述从小型高价产品逐步走向更大规模电动车的思路。",
    researchNote: "可作为后来产品、成本和规模化叙事的早期文字基线。",
    verificationNote: "这是 Tesla 官方西班牙语历史页面；原始英文旧链接会跳转，因此页面应明确标出语言版本。",
    tags: ["Tesla", "总体计划", "署名文章", "早期创业"],
  },
  {
    id: "musk-master-plan-2016",
    title: "Tesla《总体计划第二部分》",
    date: "2016-07-20",
    category: "本人文章 / 信件",
    organization: "Tesla",
    publisher: "Tesla / Elon Musk",
    official: true,
    muskRole: "本人署名文本",
    sourceFormat: "官方网页 / 文章",
    completeness: "完整文字稿",
    evidenceLevel: "S",
    access: "稳定直达",
    primaryUrl: "https://www.tesla.com/master-plan-part-deux",
    context: "署名的 Tesla 战略文章，涵盖太阳能、产品线、自动驾驶与共享车队。",
    researchNote: "适合逐项拆分愿景、产品路径与时间判断，并与后续产品和监管材料对照。",
    verificationNote: "原始 Tesla 页面；文章表达的是当时的计划与方向，不应把每项都视为已经完成的事实。",
    tags: ["Tesla", "总体计划", "FSD", "署名文章"],
  },
  {
    id: "tesla-solarcity-webcast-2016",
    title: "SolarCity 收购说明会与问答逐字稿",
    date: "2016-06-22",
    category: "投资者沟通",
    organization: "Tesla",
    publisher: "Tesla / SEC Rule 425",
    official: true,
    muskRole: "本人参与问答",
    sourceFormat: "完整文字稿",
    completeness: "完整文字稿",
    evidenceLevel: "S",
    access: "稳定直达",
    primaryUrl: "https://ir.tesla.com/_flysystem/s3/sec/000119312516629286/d40004d425-gen_0.pdf",
    context: "Tesla 就 SolarCity 收购举行的电话会和网络直播完整转录，包含利益冲突、协同、执行和时间分配追问。",
    researchNote: "少见的、可全文检索的公司交易压力场景；适合分辨问题、马斯克回答和其他发言者。",
    verificationNote: "PDF 首页明确标明活动日期和 Tesla 主办身份；逐字稿仍需按说话人姓名引用。",
    tags: ["Tesla", "SolarCity", "并购", "完整文字稿"],
  },
  {
    id: "tesla-staff-email-2018",
    title: "致全体员工的季度冲刺邮件（SEC 附件）",
    date: "2018-09-30",
    category: "本人文章 / 信件",
    organization: "Tesla",
    publisher: "Tesla / SEC 8-K 附件",
    official: true,
    muskRole: "本人署名文本",
    sourceFormat: "完整文字稿",
    completeness: "完整文字稿",
    evidenceLevel: "S",
    access: "稳定直达",
    primaryUrl: "https://www.sec.gov/Archives/edgar/data/1318605/000156459018023716/tsla-ex991_6.htm",
    context: "以马斯克署名、后被纳入 8-K 附件公开的全员邮件。",
    researchNote: "这是罕见的内部管理表达的一手文本，可与公开投资者沟通区分开阅读。",
    verificationNote: "公开版本来自 Tesla 向 SEC 提交的附件；不能据此推断全部内部沟通方式。",
    tags: ["Tesla", "员工沟通", "署名邮件", "SEC 附件"],
  },
  {
    id: "tesla-autonomy-day-2019",
    title: "Tesla Autonomy Day",
    date: "2019-04-22",
    category: "公司活动",
    organization: "Tesla",
    publisher: "Tesla / YouTube",
    official: true,
    muskRole: "本人完整发言",
    sourceFormat: "完整视频",
    completeness: "完整视频",
    evidenceLevel: "S",
    access: "可能受地区 / 平台限制",
    primaryUrl: "https://www.youtube.com/watch?v=Ucp0TTmvqOE",
    context: "面向投资者和公众的技术活动，涵盖 FSD 芯片、神经网络、车队数据与 Robotaxi 构想。",
    researchNote: "适合按时间码拆解技术叙事、产品判断和商业化预期。",
    verificationNote: "活动有多位发言者；记录时必须区分马斯克、工程负责人和主持人的话。",
    tags: ["Tesla", "FSD", "Robotaxi", "完整视频"],
  },
  {
    id: "tesla-model-s-plaid-2021",
    title: "Model S Plaid 交付活动",
    date: "2021-06-10",
    category: "产品发布",
    organization: "Tesla",
    publisher: "Tesla / YouTube",
    official: true,
    muskRole: "本人完整发言",
    sourceFormat: "完整视频",
    completeness: "完整视频",
    evidenceLevel: "S",
    access: "可能受地区 / 平台限制",
    primaryUrl: "https://www.youtube.com/watch?v=kUmkbzQ-BS0",
    context: "面向交付和产品性能的现场发布活动。",
    researchNote: "用于观察产品主张、舞台演示和量产产品之间的连接方式。",
    verificationNote: "Tesla 官方公开视频；引用具体性能或承诺前应回看相应时间码。",
    tags: ["Tesla", "Model S", "产品发布", "完整视频"],
  },
  {
    id: "tesla-ai-day-2021",
    title: "Tesla AI Day 2021",
    date: "2021-08-19",
    category: "公司活动",
    organization: "Tesla",
    publisher: "Tesla / YouTube",
    official: true,
    muskRole: "本人完整发言",
    sourceFormat: "完整视频",
    completeness: "完整视频",
    evidenceLevel: "S",
    access: "可能受地区 / 平台限制",
    primaryUrl: "https://www.youtube.com/watch?v=j0z4FweCy4M",
    context: "AI、Dojo、自动驾驶和 Optimus 招聘叙事的长时活动。",
    researchNote: "适合在技术展示、人才招募和长期产品方向之间做区分。",
    verificationNote: "官方完整活动，但包含多位工程师；不要把整场全部标成马斯克言论。",
    tags: ["Tesla", "AI", "Dojo", "Optimus"],
  },
  {
    id: "tesla-ai-day-2022",
    title: "Tesla AI Day 2022",
    date: "2022-09-30",
    category: "公司活动",
    organization: "Tesla",
    publisher: "Tesla / YouTube",
    official: true,
    muskRole: "本人完整发言",
    sourceFormat: "完整视频",
    completeness: "完整视频",
    evidenceLevel: "S",
    access: "可能受地区 / 平台限制",
    primaryUrl: "https://www.youtube.com/watch?v=ODSJsviD_SU",
    context: "围绕训练数据、Dojo、端到端 AI、Optimus 与自动驾驶工程路线的公开活动。",
    researchNote: "可用来分开记录现场演示、工程计划和已向用户开放的能力。",
    verificationNote: "技术展示不等于产品已经达成；应保存发言段和演示段的不同时间码。",
    tags: ["Tesla", "AI", "FSD", "Optimus"],
  },
  {
    id: "tesla-semi-delivery-2022",
    title: "Tesla Semi 交付活动",
    date: "2022-12-01",
    category: "产品发布",
    organization: "Tesla",
    publisher: "Tesla / YouTube",
    official: true,
    muskRole: "本人完整发言",
    sourceFormat: "完整视频",
    completeness: "完整视频",
    evidenceLevel: "S",
    access: "可能受地区 / 平台限制",
    primaryUrl: "https://www.youtube.com/watch?v=LtOqU2o81iI",
    context: "Tesla Semi 的交付、商用产品和技术指标发布活动。",
    researchNote: "补足乘用车以外的产品发布和商用叙事场景。",
    verificationNote: "Tesla YouTube 公开视频；页面编辑时建议补马斯克发言起止时间。",
    tags: ["Tesla", "Semi", "商用产品", "完整视频"],
  },
  {
    id: "tesla-investor-day-2023",
    title: "Tesla Investor Day 2023",
    date: "2023-03-01",
    category: "公司活动",
    organization: "Tesla",
    publisher: "Tesla / YouTube",
    official: true,
    muskRole: "本人完整发言",
    sourceFormat: "完整视频",
    completeness: "完整视频",
    evidenceLevel: "S",
    access: "可能受地区 / 平台限制",
    primaryUrl: "https://www.youtube.com/watch?v=Hl1zEzVUV7w",
    context: "Master Plan 3、制造、能源和长期战略的公开活动。",
    researchNote: "适合比较宏观使命、制造路线和资本市场叙事如何在同一场活动中呈现。",
    verificationNote: "马斯克只占部分环节；其余内容由其他 Tesla 高管发言。",
    tags: ["Tesla", "Investor Day", "Master Plan 3", "完整视频"],
  },
  {
    id: "tesla-cybertruck-delivery-2023",
    title: "Cybertruck 交付活动",
    date: "2023-11-30",
    category: "产品发布",
    organization: "Tesla",
    publisher: "Tesla / YouTube",
    official: true,
    muskRole: "本人完整发言",
    sourceFormat: "完整视频",
    completeness: "完整视频",
    evidenceLevel: "S",
    access: "可能受地区 / 平台限制",
    primaryUrl: "https://www.youtube.com/watch?v=FU6r3BmlgBM",
    context: "Cybertruck 产品能力、演示和正式交付的活动记录。",
    researchNote: "可用于对照产品发布时的描述、现场条件和后续量产问答。",
    verificationNote: "应把舞台演示和普通用户可得能力分开标注。",
    tags: ["Tesla", "Cybertruck", "交付", "完整视频"],
  },
  {
    id: "tesla-we-robot-2024",
    title: "We, Robot：Cybercab 与 Optimus 官方活动页",
    date: "2024-10-10",
    category: "产品发布",
    organization: "Tesla",
    publisher: "Tesla",
    official: true,
    muskRole: "本人署名文本",
    sourceFormat: "官方网页 / 文章",
    completeness: "官方摘录 / 公告",
    evidenceLevel: "S",
    access: "稳定直达",
    primaryUrl: "https://www.tesla.com/en_in/we-robot",
    context: "Tesla 对 Cybercab、Optimus 和现场活动的官方摘录，含署名马斯克引语。",
    researchNote: "作为稳定的官方活动入口，可与视频记录、财报问答和监管材料并列。",
    verificationNote: "这是官方摘录页面，不应标注为完整活动视频或完整逐字稿。",
    tags: ["Tesla", "Cybercab", "Optimus", "官方摘录"],
  },
  ...teslaCalls,
  {
    id: "sec-musk-testimony-2018",
    title: "Elon Musk 在 SEC 调查中的完整受询视频与逐字稿",
    date: "2018-08-29",
    publishedAt: "2026-06-01",
    category: "监管与法律",
    organization: "监管 / 法院",
    publisher: "U.S. Securities and Exchange Commission",
    official: true,
    muskRole: "本人参与问答",
    sourceFormat: "完整视频",
    completeness: "完整视频",
    evidenceLevel: "S",
    access: "稳定直达",
    primaryUrl: "https://www.sec.gov/enforce/elon-musk-testimony-videos",
    supplementaryUrl: "https://www.sec.gov/files/elon-musk-testimony-transcript.pdf",
    supplementaryLabel: "打开官方逐字稿",
    context: "与 2018 年 Tesla 私有化表述有关的 SEC 调查证词；SEC 后来公开了 9 段完整受询视频与依法删节的逐字稿。",
    researchNote: "这是少见的律师追问、完整原话与可观察非语言线索都可回看的正式材料，应作为法律压力场景的优先入口。",
    verificationNote: "证词发生于 2018-08-29，SEC 于 2026-06-01 公开视频与逐字稿。必须保留问答上下文，不能把 SEC 的问题或陈述误写成马斯克承认的事实。",
    tags: ["SEC", "证词", "法律压力", "完整视频", "官方逐字稿"],
  },
  {
    id: "sec-complaint-2018",
    title: "SEC 对 Elon Musk 的 2018 年起诉书",
    date: "2018-09-27",
    category: "监管与法律",
    organization: "监管 / 法院",
    publisher: "U.S. Securities and Exchange Commission",
    official: true,
    muskRole: "公司 / 监管行动记录",
    sourceFormat: "官方 PDF / 法律文件",
    completeness: "行动记录",
    evidenceLevel: "S",
    access: "稳定直达",
    primaryUrl: "https://www.sec.gov/files/litigation/complaints/2018/comp-pr2018-219.pdf",
    context: "监管机构对 2018 年私有化相关公开表述提出的起诉文件，含相关帖子和指控的原始转述。",
    researchNote: "为公开言论提供法律语境；应与证词、和解文件和公司披露一起阅读。",
    verificationNote: "起诉书记录的是 SEC 的指控，不等于事实裁判或人格判断。",
    tags: ["SEC", "诉状", "公开表述", "监管"],
  },
  {
    id: "tesla-sec-settlement-2018",
    title: "Tesla 对 SEC 和解的 8-K 披露",
    date: "2018-10-16",
    category: "监管与法律",
    organization: "Tesla",
    publisher: "Tesla / SEC 8-K",
    official: true,
    muskRole: "公司 / 监管行动记录",
    sourceFormat: "官方 PDF / 法律文件",
    completeness: "行动记录",
    evidenceLevel: "S",
    access: "稳定直达",
    primaryUrl: "https://www.sec.gov/Archives/edgar/data/1318605/000156459018024373/tsla-8k_20181016.htm",
    context: "Tesla 对与 SEC 和解及相关公司治理变化的正式披露。",
    researchNote: "适合作为“公开表述—监管行动—公司治理变化”的对照节点。",
    verificationNote: "公司披露的是正式行动记录，不是马斯克本人对动机的解释。",
    tags: ["Tesla", "SEC", "和解", "治理"],
  },
  {
    id: "nhtsa-recall-2023",
    title: "Tesla 23V-838 Part 573 安全召回原始报告",
    date: "2023-12-12",
    category: "监管与法律",
    organization: "监管 / 法院",
    publisher: "Tesla 向 NHTSA 的法定报送",
    official: true,
    muskRole: "公司 / 监管行动记录",
    sourceFormat: "官方 PDF / 法律文件",
    completeness: "行动记录",
    evidenceLevel: "S",
    access: "稳定直达",
    primaryUrl: "https://static.nhtsa.gov/odi/rcl/2023/RCLRPT-23V838-8276.PDF",
    context: "Tesla 对 Autopilot 召回及软件补救的原始法定报送。",
    researchNote: "将公司和个人的产品叙事放回独立监管动作中核验。",
    verificationNote: "这不是马斯克本人发言；应表述为 Tesla 的法定公司报送。",
    tags: ["NHTSA", "Autopilot", "召回", "行动记录"],
  },
  {
    id: "nhtsa-query-2024",
    title: "NHTSA 对 23V-838 补救充分性的调查问询",
    date: "2024-04-25",
    category: "监管与法律",
    organization: "监管 / 法院",
    publisher: "National Highway Traffic Safety Administration",
    official: true,
    muskRole: "公司 / 监管行动记录",
    sourceFormat: "官方 PDF / 法律文件",
    completeness: "行动记录",
    evidenceLevel: "S",
    access: "稳定直达",
    primaryUrl: "https://static.nhtsa.gov/odi/inv/2024/INOA-RQ24009-12046.pdf",
    context: "NHTSA 就此前 Autopilot 召回补救是否充分展开的调查问询。",
    researchNote: "帮助避免只用公司自己的产品解释来判断问题和后续行动。",
    verificationNote: "这是监管机关的文件和判断框架，不是对马斯克个人动机的判断。",
    tags: ["NHTSA", "Autopilot", "监管问询", "行动记录"],
  },
  {
    id: "nhtsa-completion-2024",
    title: "23V-838 召回季度完成率报告",
    date: "2024-07-29",
    category: "监管与法律",
    organization: "监管 / 法院",
    publisher: "Tesla 向 NHTSA 的法定报送",
    official: true,
    muskRole: "公司 / 监管行动记录",
    sourceFormat: "官方 PDF / 法律文件",
    completeness: "行动记录",
    evidenceLevel: "S",
    access: "稳定直达",
    primaryUrl: "https://static.nhtsa.gov/odi/rcl/2023/RCLQRT-23V838-0414.PDF",
    context: "与 23V-838 相关的后续季度完成率报送。",
    researchNote: "用于记录补救实施进度，而不是代替对产品能力、风险或个人观点的判断。",
    verificationNote: "文件日期与原始召回报告不同；因此在资料库中独立建档，避免混淆。",
    tags: ["NHTSA", "Autopilot", "召回进度", "行动记录"],
  },
  {
    id: "spacex-iac-2016",
    title: "Making Humans a Multiplanetary Species（IAC 2016）",
    date: "2016-09-27",
    category: "公司活动",
    organization: "SpaceX",
    publisher: "SpaceX / YouTube",
    official: true,
    muskRole: "本人完整发言",
    sourceFormat: "完整视频",
    completeness: "完整视频",
    evidenceLevel: "S",
    access: "可能受地区 / 平台限制",
    primaryUrl: "https://www.youtube.com/watch?v=H7Uyfqi_TE8",
    context: "首次系统说明大型火箭与火星运输设想的完整演讲。",
    researchNote: "适合与 2017、2019、2022 年版本对照设计变化、成本假设和时间判断。",
    verificationNote: "愿景和时间表必须与后续工程测试分开记录。",
    tags: ["SpaceX", "Mars", "IAC", "完整视频"],
  },
  {
    id: "spacex-iac-2017",
    title: "Making Life Multiplanetary（IAC 2017）",
    date: "2017-09-28",
    category: "公司活动",
    organization: "SpaceX",
    publisher: "SpaceX / YouTube",
    official: true,
    muskRole: "本人完整发言",
    sourceFormat: "完整视频",
    completeness: "完整视频",
    evidenceLevel: "S",
    access: "可能受地区 / 平台限制",
    primaryUrl: "https://www.youtube.com/watch?v=tdUX3ypDVwI",
    context: "围绕 BFR / Starship 路线、成本和迭代策略的完整演讲。",
    researchNote: "与 2016 版本配对，可观察公开工程叙事如何更新。",
    verificationNote: "应当用完整视频保留问答和语气；单独截取的结论需要时间码。",
    tags: ["SpaceX", "Starship", "Mars", "完整视频"],
  },
  {
    id: "spacex-iac-2017-transcript",
    title: "Making Life Multiplanetary（官方节录稿）",
    date: "2017-09-28",
    category: "公司活动",
    organization: "SpaceX",
    publisher: "SpaceX",
    official: true,
    muskRole: "本人完整发言",
    sourceFormat: "完整文字稿",
    completeness: "官方摘录 / 公告",
    evidenceLevel: "S",
    access: "稳定直达",
    primaryUrl: "https://www.spacex.com/media/making_life_multiplanetary_transcript_2017.pdf",
    context: "SpaceX 发布的 IAC 2017 演讲文字节录。",
    researchNote: "便于搜索和建立时间码索引，可和完整视频相互校验。",
    verificationNote: "页面应标为官方节录，而非替代完整逐字稿。",
    tags: ["SpaceX", "Starship", "文字稿", "官方节录"],
  },
  {
    id: "spacex-starship-update-2019",
    title: "Starship Update 2019",
    date: "2019-09-28",
    category: "公司活动",
    organization: "SpaceX",
    publisher: "SpaceX / YouTube",
    official: true,
    muskRole: "本人完整发言",
    sourceFormat: "完整视频",
    completeness: "完整视频",
    evidenceLevel: "S",
    access: "可能受地区 / 平台限制",
    primaryUrl: "https://www.youtube.com/watch?v=sOpMrVnjYeY",
    context: "关于不锈钢方案、生产、设计删减和 Starship 工程路径的现场发布。",
    researchNote: "适合作为工程取舍、制造速度和目标调整的原始口述记录。",
    verificationNote: "演讲中有预测和设想；应与后续测试和公司记录分别标注。",
    tags: ["SpaceX", "Starship", "工程迭代", "完整视频"],
  },
  {
    id: "spacex-starship-update-2022",
    title: "Starship Update 2022",
    date: "2022-02-10",
    category: "公司活动",
    organization: "SpaceX",
    publisher: "SpaceX / YouTube",
    official: true,
    muskRole: "本人完整发言",
    sourceFormat: "完整视频",
    completeness: "完整视频",
    evidenceLevel: "S",
    access: "可能受地区 / 平台限制",
    primaryUrl: "https://www.youtube.com/live/3N7L8Xhkzqo",
    context: "在 Starbase 讲述 Raptor 2、回收塔、制造与测试目标的现场更新。",
    researchNote: "与后续 IFT 测试页形成“公开说明—测试结果”的可比对链。",
    verificationNote: "直播可能有平台和地区限制；页面应保留原始公开视频地址。",
    tags: ["SpaceX", "Starship", "Raptor", "完整视频"],
  },
  {
    id: "spacex-mars-2025",
    title: "Mars 2026：Starship 谈话与计划更新",
    date: "2025-05-28",
    category: "公司活动",
    organization: "SpaceX",
    publisher: "SpaceX",
    official: true,
    muskRole: "本人完整发言",
    sourceFormat: "官方网页 / 文章",
    completeness: "官方摘录 / 公告",
    evidenceLevel: "S",
    access: "稳定直达",
    primaryUrl: "https://www.spacex.com/content/starship-talks/mars-2026",
    context: "SpaceX 发布的 Starship / 火星计划更新入口，说明马斯克讲述未来火星任务计划。",
    researchNote: "补足近期 Starship 叙事，可与 IFT-7 至 IFT-9 的实际测试记录并列。",
    verificationNote: "按页面实际呈现方式记录视频或文本；计划不等于已实现结果。",
    tags: ["SpaceX", "Mars", "Starship", "近期更新"],
  },
  {
    id: "spacex-sn10",
    title: "Starship 高空测试 SN10",
    date: "2021-03-03",
    category: "测试 / 行动记录",
    organization: "SpaceX",
    publisher: "SpaceX",
    official: true,
    muskRole: "公司 / 监管行动记录",
    sourceFormat: "官方网页 / 文章",
    completeness: "行动记录",
    evidenceLevel: "S",
    access: "稳定直达",
    primaryUrl: "https://www.spacex.com/launches/starship-sn10",
    context: "SN10 高空起飞、下降和触地后的异常记录。",
    researchNote: "可作为工程测试过程的行动证据，与人的言行资料区分显示。",
    verificationNote: "不是马斯克发言；不以单次测试结果概括个人管理风格。",
    tags: ["SpaceX", "Starship", "SN10", "测试"],
  },
  {
    id: "spacex-sn15",
    title: "Starship 高空测试 SN15",
    date: "2021-05-05",
    category: "测试 / 行动记录",
    organization: "SpaceX",
    publisher: "SpaceX",
    official: true,
    muskRole: "公司 / 监管行动记录",
    sourceFormat: "官方网页 / 文章",
    completeness: "行动记录",
    evidenceLevel: "S",
    access: "稳定直达",
    primaryUrl: "https://www.spacex.com/launches/starship-sn15",
    context: "原型机完成高空起飞、下降和着陆的官方测试记录。",
    researchNote: "与 SN10 配对，显示相邻测试节点的可观察变化。",
    verificationNote: "公司行动记录，只能说明公开测试结果。",
    tags: ["SpaceX", "Starship", "SN15", "测试"],
  },
  ...starshipFlights,
  {
    id: "neuralink-paper-2019",
    title: "An Integrated Brain-Machine Interface Platform With Thousands of Channels",
    date: "2019-10",
    category: "学术发表",
    organization: "Neuralink",
    publisher: "Journal of Medical Internet Research / Neuralink authors",
    official: false,
    muskRole: "本人署名文本",
    sourceFormat: "学术论文",
    completeness: "完整文字稿",
    evidenceLevel: "A",
    access: "稳定直达",
    primaryUrl: "https://www.jmir.org/2019/10/e16194/",
    context: "马斯克列名合著者的 Neuralink 技术论文。",
    researchNote: "重要的技术一手文字来源，但作者署名不表示每一段都是他的个人口述观点。",
    verificationNote: "学术论文应按作者和具体实验内容引用，不能扩大为临床有效性结论。",
    tags: ["Neuralink", "论文", "脑机接口", "合著"],
  },
  {
    id: "neuralink-launch-2019",
    title: "Neuralink Launch Event",
    date: "2019-07-16",
    category: "公司活动",
    organization: "Neuralink",
    publisher: "Neuralink / YouTube",
    official: true,
    muskRole: "本人完整发言",
    sourceFormat: "完整视频",
    completeness: "完整视频",
    evidenceLevel: "S",
    access: "可能受地区 / 平台限制",
    primaryUrl: "https://www.youtube.com/watch?v=r-vbh3t7WVI",
    context: "Neuralink 首次公开发布会，包含马斯克的技术愿景和团队介绍。",
    researchNote: "适合与论文和后续临床更新分层阅读。",
    verificationNote: "发布会并非临床疗效证据；技术设想和试验阶段需明确区分。",
    tags: ["Neuralink", "脑机接口", "发布会", "完整视频"],
  },
  {
    id: "neuralink-update-2020",
    title: "Neuralink Progress Update, Summer 2020",
    date: "2020-08-28",
    category: "公司活动",
    organization: "Neuralink",
    publisher: "Neuralink / YouTube",
    official: true,
    muskRole: "本人完整发言",
    sourceFormat: "完整视频",
    completeness: "完整视频",
    evidenceLevel: "S",
    access: "可能受地区 / 平台限制",
    primaryUrl: "https://www.youtube.com/watch?v=DVvmgjBL74w",
    context: "设备和动物演示、愿景与问答的公开更新。",
    researchNote: "保留演示、发言和问答的完整语境，避免单独截取片段。",
    verificationNote: "动物演示不应外推为人体疗效或安全性结论。",
    tags: ["Neuralink", "脑机接口", "演示", "完整视频"],
  },
  {
    id: "neuralink-pager-2021",
    title: "Pager Plays MindPong",
    date: "2021-04-18",
    category: "公司公告",
    organization: "Neuralink",
    publisher: "Neuralink",
    official: true,
    muskRole: "公司 / 监管行动记录",
    sourceFormat: "官方网页 / 文章",
    completeness: "官方摘录 / 公告",
    evidenceLevel: "S",
    access: "稳定直达",
    primaryUrl: "https://neuralink.com/updates/pager-plays-mindpong/",
    context: "Neuralink 对 Pager 演示的原始说明。",
    researchNote: "放在公司行动与演示栏，而非马斯克个人发言栏。",
    verificationNote: "医学、动物福利和安全性主张应另有独立研究或监管语境。",
    tags: ["Neuralink", "演示", "公司公告", "行动记录"],
  },
  {
    id: "neuralink-show-tell-2022",
    title: "Neuralink Show and Tell 2022",
    date: "2022-11-30",
    category: "公司活动",
    organization: "Neuralink",
    publisher: "Neuralink / YouTube",
    official: true,
    muskRole: "本人完整发言",
    sourceFormat: "完整视频",
    completeness: "完整视频",
    evidenceLevel: "S",
    access: "可能受地区 / 平台限制",
    primaryUrl: "https://www.youtube.com/watch?v=YreDYmXTYi4",
    context: "Neuralink 团队的长时展示，包含愿景、工程细节、招募和问答。",
    researchNote: "可按发言人、技术演示和问答分段归档。",
    verificationNote: "完整活动有多位发言者，引用前须定位马斯克段落。",
    tags: ["Neuralink", "脑机接口", "招募", "完整视频"],
  },
  {
    id: "neuralink-prime-recruitment-2023",
    title: "首个人体临床试验开放招募",
    date: "2023-09-19",
    category: "公司公告",
    organization: "Neuralink",
    publisher: "Neuralink",
    official: true,
    muskRole: "公司 / 监管行动记录",
    sourceFormat: "官方网页 / 文章",
    completeness: "官方摘录 / 公告",
    evidenceLevel: "S",
    access: "稳定直达",
    primaryUrl: "https://neuralink.com/updates/first-clinical-trial-open-for-recruitment/",
    context: "Neuralink 就 PRIME 研究招募范围和试验阶段发布的原始公告。",
    researchNote: "作为临床阶段的公司行动记录，补足发布会以外的事实层。",
    verificationNote: "研究性临床试验不保证获益；不可将公告写成已证实疗效。",
    tags: ["Neuralink", "PRIME", "临床试验", "行动记录"],
  },
  {
    id: "neuralink-prime-progress-2024",
    title: "PRIME Study Progress Update",
    date: "2024-04-12",
    category: "公司公告",
    organization: "Neuralink",
    publisher: "Neuralink",
    official: true,
    muskRole: "公司 / 监管行动记录",
    sourceFormat: "官方网页 / 文章",
    completeness: "官方摘录 / 公告",
    evidenceLevel: "S",
    access: "稳定直达",
    primaryUrl: "https://neuralink.com/updates/prime-study-progress-update/",
    context: "第一例植入与设备机理进度的公司公开说明。",
    researchNote: "将公司公开进展与发布会话语分别存档。",
    verificationNote: "有效性和安全性不应超出页面自身表述。",
    tags: ["Neuralink", "PRIME", "临床进展", "行动记录"],
  },
  {
    id: "neuralink-summer-2025",
    title: "Neuralink Update, Summer 2025",
    date: "2025-06-27",
    category: "公司活动",
    organization: "Neuralink",
    publisher: "Neuralink / YouTube",
    official: true,
    muskRole: "本人参与问答",
    sourceFormat: "完整视频",
    completeness: "完整视频",
    evidenceLevel: "S",
    access: "可能受地区 / 平台限制",
    primaryUrl: "https://www.youtube.com/watch?v=FASMejN_5gs",
    context: "近期技术与进度更新；马斯克在开头进行愿景 / 进度发言，后续为团队技术说明。",
    researchNote: "应在首次精编时补马斯克出场起止时间，而不是把团队段落归给他。",
    verificationNote: "公开视频完整，但不能外推出临床结果。",
    tags: ["Neuralink", "脑机接口", "进度更新", "完整视频"],
  },
  {
    id: "xai-grok-2023",
    title: "Announcing Grok",
    date: "2023-11-03",
    category: "公司公告",
    organization: "xAI",
    publisher: "xAI",
    official: true,
    muskRole: "公司 / 监管行动记录",
    sourceFormat: "官方网页 / 文章",
    completeness: "官方摘录 / 公告",
    evidenceLevel: "S",
    access: "稳定直达",
    primaryUrl: "https://x.ai/news/grok",
    context: "xAI 对 Grok 首次发布的原始产品说明。",
    researchNote: "是公司产品叙事的一手记录，不应自动等同为马斯克个人说法。",
    verificationNote: "产品性能与能力主张应保留发布版本和测试条件。",
    tags: ["xAI", "Grok", "产品发布", "行动记录"],
  },
  {
    id: "xai-grok-open-2024",
    title: "Open Release of Grok-1",
    date: "2024-03-17",
    category: "公司公告",
    organization: "xAI",
    publisher: "xAI",
    official: true,
    muskRole: "公司 / 监管行动记录",
    sourceFormat: "官方网页 / 文章",
    completeness: "官方摘录 / 公告",
    evidenceLevel: "S",
    access: "稳定直达",
    primaryUrl: "https://x.ai/news/grok-os",
    context: "xAI 公布 Grok-1 开放权重的原始行动公告。",
    researchNote: "将“开放权重”作为公司选择的可核验行动，而不是只作为抽象价值判断。",
    verificationNote: "请按公告中的具体许可和版本范围理解开放。",
    tags: ["xAI", "Grok", "开放权重", "行动记录"],
  },
  {
    id: "xai-grok-2-2024",
    title: "Grok-2 Beta Release",
    date: "2024-08-13",
    category: "公司公告",
    organization: "xAI",
    publisher: "xAI",
    official: true,
    muskRole: "公司 / 监管行动记录",
    sourceFormat: "官方网页 / 文章",
    completeness: "官方摘录 / 公告",
    evidenceLevel: "S",
    access: "稳定直达",
    primaryUrl: "https://x.ai/news/grok-2",
    context: "Grok-2 Beta 的模型、产品与性能叙事。",
    researchNote: "可记录公司公开的版本变化与比较口径。",
    verificationNote: "基准和性能数据为公司自报时，应明确标识。",
    tags: ["xAI", "Grok", "Beta", "产品发布"],
  },
  {
    id: "xai-grok-3-2025",
    title: "Grok 3 Beta — The Age of Reasoning Agents",
    date: "2025-02-19",
    category: "公司公告",
    organization: "xAI",
    publisher: "xAI",
    official: true,
    muskRole: "公司 / 监管行动记录",
    sourceFormat: "官方网页 / 文章",
    completeness: "官方摘录 / 公告",
    evidenceLevel: "S",
    access: "稳定直达",
    primaryUrl: "https://x.ai/news/grok-3",
    context: "Grok 3 的推理、DeepSearch 和产品取向说明。",
    researchNote: "补足 xAI 公司层面的模型路线与产品决策。",
    verificationNote: "模型主张应与独立测试和实际可用版本区分。",
    tags: ["xAI", "Grok", "推理", "产品发布"],
  },
  {
    id: "xai-grok-4-2025",
    title: "Grok 4",
    date: "2025-07-09",
    category: "公司公告",
    organization: "xAI",
    publisher: "xAI",
    official: true,
    muskRole: "公司 / 监管行动记录",
    sourceFormat: "官方网页 / 文章",
    completeness: "官方摘录 / 公告",
    evidenceLevel: "S",
    access: "稳定直达",
    primaryUrl: "https://x.ai/news/grok-4",
    context: "Grok 4 的训练、强化学习、工具调用与产品策略说明。",
    researchNote: "用于记录公司在模型与产品上的公开动作。",
    verificationNote: "任何能力或基准结论都应带上公告的版本和条件。",
    tags: ["xAI", "Grok", "工具调用", "产品发布"],
  },
  {
    id: "x-transparency-2023",
    title: "A New Era of Transparency for Twitter",
    date: "2023-03-31",
    category: "公司公告",
    organization: "X",
    publisher: "Twitter / X",
    official: true,
    muskRole: "公司 / 监管行动记录",
    sourceFormat: "官方网页 / 文章",
    completeness: "官方摘录 / 公告",
    evidenceLevel: "S",
    access: "稳定直达",
    primaryUrl: "https://blog.x.com/en_us/topics/company/2023/a-new-era-of-transparency-for-twitter",
    context: "Twitter / X 对算法开源与透明度动作的官方公告。",
    researchNote: "把收购后平台变化作为公司公开行动记录，而不是直接归为马斯克的访谈观点。",
    verificationNote: "公司对透明度的自述，适合与独立研究或后续材料交叉核验。",
    tags: ["X", "算法", "透明度", "行动记录"],
  },
  {
    id: "x-building-future-2023",
    title: "Building the Future of X",
    date: "2023-08-02",
    category: "公司公告",
    organization: "X",
    publisher: "X",
    official: true,
    muskRole: "公司 / 监管行动记录",
    sourceFormat: "官方网页 / 文章",
    completeness: "官方摘录 / 公告",
    evidenceLevel: "S",
    access: "稳定直达",
    primaryUrl: "https://blog.x.com/en_us/topics/company/2023/building-the-future-of-x",
    context: "X 对订阅、验证、内容和支付方向的产品变更梳理。",
    researchNote: "提供收购后公司动作的时间索引。",
    verificationNote: "是公司公开说法；数据和效果主张需区分事实、公司自报与外部验证。",
    tags: ["X", "产品变更", "平台", "行动记录"],
  },
  {
    id: "x-community-notes-2023",
    title: "X’s Community-Led Approach",
    date: "2023-10-24",
    category: "公司公告",
    organization: "X",
    publisher: "X",
    official: true,
    muskRole: "公司 / 监管行动记录",
    sourceFormat: "官方网页 / 文章",
    completeness: "官方摘录 / 公告",
    evidenceLevel: "S",
    access: "稳定直达",
    primaryUrl: "https://blog.x.com/en_us/topics/company/2023/xs-community-led-approach-tackling-inaccurate-and-misleading-information",
    context: "X 对 Community Notes 机制与效果的原始说明。",
    researchNote: "可作为平台机制公开化的公司层记录。",
    verificationNote: "效果数据为公司叙述时，应另配独立评估。",
    tags: ["X", "Community Notes", "平台治理", "行动记录"],
  },
  {
    id: "x-one-year-2023",
    title: "One Year In, the Future of X Is Bright",
    date: "2023-10-26",
    category: "公司公告",
    organization: "X",
    publisher: "X",
    official: true,
    muskRole: "公司 / 监管行动记录",
    sourceFormat: "官方网页 / 文章",
    completeness: "官方摘录 / 公告",
    evidenceLevel: "S",
    access: "稳定直达",
    primaryUrl: "https://blog.x.com/en_us/topics/company/2023/one-year-in",
    context: "X 对产品、组织、营收和安全主张的周年汇总。",
    researchNote: "用于建立收购后一年的公司公开叙事索引。",
    verificationNote: "指标主要来自公司自报，不能替代外部核验。",
    tags: ["X", "周年总结", "平台", "行动记录"],
  },
  {
    id: "x-conflict-safety-2023",
    title: "Maintaining the Safety of X in Times of Conflict",
    date: "2023-11-14",
    category: "公司公告",
    organization: "X",
    publisher: "X",
    official: true,
    muskRole: "公司 / 监管行动记录",
    sourceFormat: "官方网页 / 文章",
    completeness: "官方摘录 / 公告",
    evidenceLevel: "S",
    access: "稳定直达",
    primaryUrl: "https://blog.x.com/en_us/topics/company/2023/maintaining-the-safety-of-x-in-times-of-conflict",
    context: "危机期的平台安全和执行措施说明。",
    researchNote: "补足危机沟通的公司行动层材料。",
    verificationNote: "应配合透明度、监管和独立观察材料，而不是当作完整事实结论。",
    tags: ["X", "危机沟通", "平台安全", "行动记录"],
  },
  {
    id: "ted-2013",
    title: "TED 2013：The mind behind Tesla, SpaceX, SolarCity",
    date: "2013-02",
    category: "采访",
    organization: "媒体采访",
    publisher: "TED",
    official: false,
    muskRole: "本人参与问答",
    sourceFormat: "完整视频",
    completeness: "完整视频",
    evidenceLevel: "A",
    access: "稳定直达",
    primaryUrl: "https://www.ted.com/talks/elon_musk_the_mind_behind_tesla_spacex_solarcity",
    context: "Chris Anderson 对 Tesla、SpaceX、SolarCity 与创业方向的长访谈，页面提供视频和文字稿。",
    researchNote: "高质量早期基线材料，适合查看其公开解释的产品、能源和可复用火箭逻辑。",
    verificationNote: "媒体采访是公开问答情境，不等同于公司正式披露。",
    tags: ["TED", "采访", "Tesla", "SpaceX"],
  },
  {
    id: "bloomberg-2014",
    title: "Bloomberg 采访：Autopilot 与自动驾驶边界",
    date: "2014-10-10",
    category: "采访",
    organization: "媒体采访",
    publisher: "Bloomberg / YouTube",
    official: false,
    muskRole: "本人参与问答",
    sourceFormat: "完整视频",
    completeness: "完整视频",
    evidenceLevel: "A",
    access: "可能受地区 / 平台限制",
    primaryUrl: "https://www.youtube.com/watch?v=Bjq6tXRKfUQ",
    context: "围绕驾驶辅助、自动化和技术路线的公开视频采访。",
    researchNote: "可作为 FSD 早期公开表述的基线，但应结合完整问题和时间码引用。",
    verificationNote: "外部媒体发布的视频；在引用前确认上传版本是否完整。",
    tags: ["Bloomberg", "采访", "FSD", "早期"],
  },
  {
    id: "denmark-2015",
    title: "丹麦电视采访：高速公路自动驾驶与时间判断",
    date: "2015-09-15",
    category: "采访",
    organization: "媒体采访",
    publisher: "DR / Danish television archive",
    official: false,
    muskRole: "本人参与问答",
    sourceFormat: "完整视频",
    completeness: "完整视频",
    evidenceLevel: "A",
    access: "可能受地区 / 平台限制",
    primaryUrl: "https://www.youtube.com/watch?v=bl5vLC3Xlgc",
    context: "围绕自动驾驶路线和可能时间窗口的公开视频采访。",
    researchNote: "用于比较技术预期、产品阶段和后续公开材料。",
    verificationNote: "引用前应确认视频完整度和问题语境，避免孤立使用时间判断。",
    tags: ["采访", "FSD", "预测", "早期"],
  },
  {
    id: "time-2021",
    title: "TIME Person of the Year 2021 对谈",
    date: "2021-12-13",
    category: "采访",
    organization: "媒体采访",
    publisher: "TIME",
    official: false,
    muskRole: "本人参与问答",
    sourceFormat: "官方网页 / 文章",
    completeness: "官方摘录 / 公告",
    evidenceLevel: "A",
    access: "稳定直达",
    primaryUrl: "https://time.com/6128235/elon-musk-interview-person-of-the-year/",
    context: "TIME 主编与马斯克的公开对谈入口，涉及企业、空间、财富与公共议题。",
    researchNote: "补足技术活动以外的长访谈场景。",
    verificationNote: "网页呈现和可访问内容可能包含编辑节录；不要标成完整逐字稿。",
    tags: ["TIME", "采访", "公共议题", "媒体"],
  },
  {
    id: "lex-400-2023",
    title: "Lex Fridman Podcast #400：War, AI, Aliens, Politics, Physics…",
    date: "2023-11-10",
    category: "采访",
    organization: "媒体采访",
    publisher: "Lex Fridman",
    official: false,
    muskRole: "本人参与问答",
    sourceFormat: "完整文字稿",
    completeness: "完整文字稿",
    evidenceLevel: "A",
    access: "稳定直达",
    primaryUrl: "https://lexfridman.com/elon-musk-4-transcript",
    context: "长时播客文字稿，涵盖 AI、X、公开预测、政治、SpaceX 与个人经历等话题。",
    researchNote: "含清晰时间码，适合检索具体回答并回到对应视频段落。",
    verificationNote: "这是采访制作方发布的转录；应保留主持人的问题和语境。",
    tags: ["Lex Fridman", "采访", "AI", "X", "完整文字稿"],
  },
  {
    id: "cnbc-faber-2025",
    title: "CNBC David Faber 采访：Austin 上线前追问",
    date: "2025-05-20",
    category: "采访",
    organization: "媒体采访",
    publisher: "CNBC",
    official: false,
    muskRole: "本人参与问答",
    sourceFormat: "完整文字稿",
    completeness: "完整文字稿",
    evidenceLevel: "A",
    access: "稳定直达",
    primaryUrl: "https://www.cnbc.com/2025/05/20/cnbc-transcript-elon-musk-sits-down-with-cnbcs-david-faber-live-on-cnbc-today-.html",
    context: "围绕 Robotaxi 上线条件、时间和运营问题的连续媒体追问。",
    researchNote: "补足公司活动之外的外部追问场景。",
    verificationNote: "将文字稿视为公开回答记录；如需非语言线索应回看对应节目视频。",
    tags: ["CNBC", "采访", "Robotaxi", "媒体追问"],
  },
  {
    id: "code-conference-2021",
    title: "Code Conference 2021：Kara Swisher 现场采访",
    date: "2021-09-28",
    category: "采访",
    organization: "媒体采访",
    publisher: "Code Conference / YouTube",
    official: false,
    muskRole: "本人参与问答",
    sourceFormat: "完整视频",
    completeness: "完整视频",
    evidenceLevel: "A",
    access: "可能受地区 / 平台限制",
    primaryUrl: "https://www.youtube.com/watch?v=ESIjxVudERY",
    context: "Kara Swisher 的现场长访谈，涉及 SpaceX、Tesla、SEC、政治与 FSD 等外部追问。",
    researchNote: "补足友好型长访谈之外的现场质询场景。",
    verificationNote: "外部采访的完整性以当前公开视频为准；引用必须保留提问和前后文。",
    tags: ["Code Conference", "Kara Swisher", "采访", "媒体追问"],
  },
  {
    id: "ted-2022",
    title: "TED 2022：Twitter、Tesla 与现场未剪辑对谈",
    date: "2022-04-14",
    category: "采访",
    organization: "媒体采访",
    publisher: "TED",
    official: false,
    muskRole: "本人参与问答",
    sourceFormat: "完整视频",
    completeness: "完整视频",
    evidenceLevel: "A",
    access: "稳定直达",
    primaryUrl: "https://www.ted.com/talks/elon_musk_elon_musk_talks_twitter_tesla_and_how_his_brain_works_live_at_ted2022",
    context: "TED 标注为现场、未剪辑的长对谈，涵盖 Twitter 收购、Tesla、SpaceX 和工作方式。",
    researchNote: "稳定的长时媒体问答入口，保留与主持人交锋的完整节奏。",
    verificationNote: "TED 页面是采访情境，而不是公司或监管正式披露。",
    tags: ["TED", "采访", "Twitter", "Tesla", "完整视频"],
  },
  {
    id: "twitter-schedule-13d-2022",
    title: "Twitter 持股 Schedule 13D（马斯克签署）",
    date: "2022-04-05",
    category: "监管与法律",
    organization: "X",
    publisher: "Elon Musk / SEC EDGAR",
    official: true,
    muskRole: "本人署名文本",
    sourceFormat: "官方 PDF / 法律文件",
    completeness: "完整文字稿",
    evidenceLevel: "S",
    access: "稳定直达",
    primaryUrl: "https://www.sec.gov/Archives/edgar/data/1418091/000110465922042863/tm2211757d1_sc13d.htm",
    context: "与 Twitter 持股相关、在文件末尾由 Elon Musk 签署的 SEC 申报。",
    researchNote: "在 X 收购前期提供本人签署、可核验的法律披露记录。",
    verificationNote: "这是一份法定持股披露，不能扩大为对收购全部动机的解释。",
    tags: ["X", "Twitter", "Schedule 13D", "署名文件"],
  },
  {
    id: "twitter-v-musk-2022",
    title: "Twitter v. Musk：经核验的起诉书",
    date: "2022-07-12",
    category: "监管与法律",
    organization: "X",
    publisher: "Twitter / Delaware Court filing",
    official: true,
    muskRole: "公司 / 监管行动记录",
    sourceFormat: "官方 PDF / 法律文件",
    completeness: "行动记录",
    evidenceLevel: "S",
    access: "稳定直达",
    primaryUrl: "https://www.sec.gov/Archives/edgar/data/1418091/000119312522192993/d381911dex991.htm",
    context: "Twitter 针对收购交易提出的经核验诉状。",
    researchNote: "提供交易与法律压力的原始文书语境，可与马斯克本人签署文件、公开发言分层阅读。",
    verificationNote: "这是 Twitter 一方的法律主张，不是对事实或马斯克动机的最终裁判。",
    tags: ["X", "Twitter", "收购", "诉状"],
  },
  {
    id: "tornetta-v-musk-2024",
    title: "Tornetta v. Musk：Tesla 薪酬案衡平法院裁决",
    date: "2024-01-30",
    category: "监管与法律",
    organization: "监管 / 法院",
    publisher: "Delaware Court of Chancery",
    official: true,
    muskRole: "公司 / 监管行动记录",
    sourceFormat: "官方 PDF / 法律文件",
    completeness: "行动记录",
    evidenceLevel: "S",
    access: "稳定直达",
    primaryUrl: "https://courts.delaware.gov/Opinions/Download.aspx?id=359340",
    context: "与 Tesla 2018 年薪酬方案有关的官方法院意见书，包含庭审材料和事实认定。",
    researchNote: "补足公司治理与法律压力场景，提供独立于公司叙事的正式记录。",
    verificationNote: "法院意见可以说明裁决与所引材料，不应被简化为个人性格诊断。",
    tags: ["Tesla", "薪酬", "法院", "公司治理"],
  },
  {
    id: "sec-compel-testimony-2023",
    title: "SEC 申请强制马斯克出席证词的文件",
    date: "2023-10-05",
    category: "监管与法律",
    organization: "监管 / 法院",
    publisher: "U.S. Securities and Exchange Commission",
    official: true,
    muskRole: "公司 / 监管行动记录",
    sourceFormat: "官方 PDF / 法律文件",
    completeness: "行动记录",
    evidenceLevel: "S",
    access: "稳定直达",
    primaryUrl: "https://www.sec.gov/files/litigation/litreleases/2023/application25880.pdf",
    context: "SEC 为强制证词出席提交的官方申请文件。",
    researchNote: "将法律程序本身作为压力场景的行动记录，与后来公开证词页面配对。",
    verificationNote: "文件表达的是 SEC 的程序性主张，并非马斯克口供或司法最终结论。",
    tags: ["SEC", "证词", "法律程序", "行动记录"],
  },
  {
    id: "sec-twitter-disclosure-2025",
    title: "SEC 对 Twitter 持股披露的 2025 年起诉书",
    date: "2025-01-14",
    category: "监管与法律",
    organization: "监管 / 法院",
    publisher: "U.S. Securities and Exchange Commission",
    official: true,
    muskRole: "公司 / 监管行动记录",
    sourceFormat: "官方 PDF / 法律文件",
    completeness: "行动记录",
    evidenceLevel: "S",
    access: "稳定直达",
    primaryUrl: "https://www.sec.gov/files/litigation/complaints/2025/comp26219.pdf",
    context: "SEC 对与 Twitter 持股披露有关事项提出的官方起诉文件。",
    researchNote: "为 X 收购前期的公开文件提供后续监管语境。",
    verificationNote: "这是监管机构的指控，不是已经被本网站当作事实结论的材料。",
    tags: ["SEC", "Twitter", "持股披露", "诉状"],
  },
  {
    id: "bbc-interview-2023-clip",
    title: "BBC 2023 年采访（官方剪辑）",
    date: "2023-04-12",
    category: "采访",
    organization: "媒体采访",
    publisher: "BBC News / YouTube",
    official: false,
    muskRole: "本人参与问答",
    sourceFormat: "视频片段 / 节录",
    completeness: "官方摘录 / 公告",
    evidenceLevel: "C",
    access: "可能受地区 / 平台限制",
    primaryUrl: "https://www.youtube.com/watch?v=SKSsnsAEcn8",
    context: "BBC 发布的 2023 年 Twitter 总部采访官方剪辑，涉及裁员、错误信息和平台管理。",
    researchNote: "保留为外部质询的定位入口，但不作为完整采访材料使用。",
    verificationNote: "该视频为约 8 分钟的官方剪辑，不能当作整场采访或完整上下文。",
    tags: ["BBC", "采访", "X", "官方剪辑", "辅助定位"],
  },
  {
    id: "bill-maher-2023",
    title: "Real Time with Bill Maher：完整采访",
    date: "2023-04-28",
    category: "采访",
    organization: "媒体采访",
    publisher: "HBO / YouTube",
    official: false,
    muskRole: "本人参与问答",
    sourceFormat: "完整视频",
    completeness: "完整视频",
    evidenceLevel: "A",
    access: "可能受地区 / 平台限制",
    primaryUrl: "https://www.youtube.com/watch?v=oO8w6XcXJUs",
    context: "HBO 节目公开的完整访谈，涉及 X、言论、公共争议和企业议题。",
    researchNote: "补足不同风格主持人与更宽泛公共议题下的公开回答。",
    verificationNote: "节目采访不等于公司正式信息披露；请保留具体问题。",
    tags: ["HBO", "Bill Maher", "采访", "X"],
  },
  {
    id: "dealbook-2023",
    title: "New York Times DealBook Summit 2023：完整现场采访",
    date: "2023-11-29",
    category: "采访",
    organization: "媒体采访",
    publisher: "The New York Times / YouTube",
    official: false,
    muskRole: "本人参与问答",
    sourceFormat: "完整视频",
    completeness: "完整视频",
    evidenceLevel: "A",
    access: "可能受地区 / 平台限制",
    primaryUrl: "https://www.youtube.com/watch?v=2BfMuHDfGJI",
    context: "DealBook Summit 的完整现场采访，围绕广告商、X、声誉与业务压力进行追问。",
    researchNote: "关键的高压力媒体问答材料，适合保留追问、停顿和非语言线索。",
    verificationNote: "使用时以完整视频为准，不以新闻短片或孤立引语替代。",
    tags: ["DealBook", "NYT", "采访", "广告商", "X"],
  },
  {
    id: "whitehouse-doge-2025",
    title: "DOGE 公开说明会官方文字记录",
    date: "2025-02-11",
    category: "采访",
    organization: "监管 / 法院",
    publisher: "U.S. Government Publishing Office",
    official: true,
    muskRole: "本人参与问答",
    sourceFormat: "官方 PDF / 法律文件",
    completeness: "待人工核验",
    evidenceLevel: "C",
    access: "稳定直达",
    primaryUrl: "https://www.govinfo.gov/content/pkg/DCPD-202500253/pdf/DCPD-202500253.pdf",
    context: "2025 年 DOGE 相关公开说明会的官方文字记录。",
    researchNote: "补足政治时期的官方文字记录，并明确保留录音核验的限制。",
    verificationNote: "官方文本标示部分音频无法核验；不能把它当作完整可回看的口头记录。",
    tags: ["DOGE", "政治时期", "官方文字", "需复核"],
  },
  {
    id: "whitehouse-cabinet-2025",
    title: "白宫 2025 年 4 月 30 日内阁会议",
    date: "2025-04-30",
    category: "采访",
    organization: "监管 / 法院",
    publisher: "The White House",
    official: true,
    muskRole: "本人参与问答",
    sourceFormat: "完整视频",
    completeness: "完整视频",
    evidenceLevel: "S",
    access: "稳定直达",
    primaryUrl: "https://www.whitehouse.gov/videos/president-trump-participates-in-a-cabinet-meeting-apr-30-2025/",
    context: "白宫公开的完整内阁会议视频，马斯克在政府工作相关场景中发言。",
    researchNote: "为 2024—2026 政治时期提供可直接观看的官方视频，而非新闻转述。",
    verificationNote: "会议涉及多位政府成员；引用前需定位马斯克的具体发言段。",
    tags: ["白宫", "DOGE", "政治时期", "完整视频"],
  },
  {
    id: "whitehouse-press-2025",
    title: "白宫与 Elon Musk 共同新闻发布会",
    date: "2025-05-30",
    category: "采访",
    organization: "监管 / 法院",
    publisher: "The White House / GovInfo",
    official: true,
    muskRole: "本人参与问答",
    sourceFormat: "完整视频",
    completeness: "完整视频",
    evidenceLevel: "S",
    access: "稳定直达",
    primaryUrl: "https://www.whitehouse.gov/videos/president-trump-participates-in-a-press-conference-with-elon-musk/",
    supplementaryUrl: "https://www.govinfo.gov/content/pkg/DCPD-202500648/pdf/DCPD-202500648.pdf",
    supplementaryLabel: "打开官方文字记录",
    context: "白宫公开的新闻发布会视频，并有 GovInfo 官方文字记录可交叉查看。",
    researchNote: "让政治时期的公开问答同时保留非语言视频与可检索文字。",
    verificationNote: "应区分马斯克、总统与记者的发言；文字记录用于检索，视频用于确认语境。",
    tags: ["白宫", "政治时期", "新闻发布会", "完整视频", "文字稿"],
  },
];

export const sourceById: Record<string, EvidenceSource> = Object.fromEntries(
  sources.map((source) => [source.id, source]),
);

export const timeline: TimelineItem[] = [
  {
    id: "t-2014",
    year: "2014",
    type: "早期公开表述",
    title: "驾驶辅助与完全自动驾驶的边界",
    sourceId: "bloomberg-2014",
    context: "早期公开采访中的能力定义讨论。",
    observation: "将驾驶辅助与长期自动驾驶目标放在同一公开叙事中。",
    action: "持续以产品、技术活动和财报问答推进相关说明。",
    outcome: "为后续能力、时间判断与监管材料提供可对照的基线。",
    certainty: "已核验",
  },
  {
    id: "t-2016",
    year: "2016",
    type: "署名计划",
    title: "总体计划第二部分纳入自动驾驶与共享车队",
    sourceId: "musk-master-plan-2016",
    context: "Tesla 官方署名文章。",
    observation: "将自动驾驶、共享使用和产品路线连接为长期计划。",
    action: "之后出现技术活动、Beta、产品发布和投资者沟通。",
    outcome: "不能把计划本身等同于后来已实现的功能或服务。",
    certainty: "已核验",
  },
  {
    id: "t-2018",
    year: "2018",
    type: "投资者问答",
    title: "跨州演示与自研计算平台",
    sourceId: "tesla-q2-2018",
    context: "Tesla 季度财报电话会。",
    observation: "工程路线、演示目标和时间判断处于同一压力问答场景。",
    action: "后续以 Autonomy Day、FSD Beta 与 AI Day 延续技术叙事。",
    outcome: "原始问答可与后续的产品和监管节点进行比较。",
    certainty: "需补充",
  },
  {
    id: "t-2019",
    year: "2019",
    type: "技术活动",
    title: "Autonomy Day 与 Robotaxi 构想",
    sourceId: "tesla-autonomy-day-2019",
    context: "面向投资者和公众的技术活动。",
    observation: "芯片、数据、神经网络和商业构想被组合成一个公开框架。",
    action: "后续继续通过 Beta、AI Day、财报问答和活动说明推进。",
    outcome: "技术展示、时间判断和实际服务范围必须分开追踪。",
    certainty: "已核验",
  },
  {
    id: "t-2020",
    year: "2020",
    type: "产品阶段",
    title: "FSD Beta 与规模化沟通",
    sourceId: "tesla-q3-2020",
    context: "季度财报电话会中的管理层与分析师问答。",
    observation: "测试、功能表达、规模预期和商业模型不处在同一成熟度。",
    action: "持续公开技术活动和后续版本信息。",
    outcome: "需要分别记录用户可用范围、版本条件和后续监管材料。",
    certainty: "需补充",
  },
  {
    id: "t-2022",
    year: "2022",
    type: "技术活动",
    title: "AI Day：数据、训练与 Dojo",
    sourceId: "tesla-ai-day-2022",
    context: "以自动驾驶和 AI 基础设施为重点的公开活动。",
    observation: "叙事重点扩展到数据闭环、训练和计算基础设施。",
    action: "后续在 Investor Day 和财报问答中继续出现 AI 与产品路线。",
    outcome: "技术展示和产品交付间仍需用独立证据连接。",
    certainty: "已核验",
  },
  {
    id: "t-2023-regulation",
    year: "2023",
    type: "监管行动",
    title: "23V-838 召回原始报告",
    sourceId: "nhtsa-recall-2023",
    context: "Tesla 向 NHTSA 提交的法定召回报送。",
    observation: "产品叙事之外存在独立的监管动作与补救记录。",
    action: "随后出现完成率报送和补救充分性调查。",
    outcome: "研究能力边界时必须并列查看监管材料。",
    certainty: "已核验",
  },
  {
    id: "t-2024",
    year: "2024",
    type: "产品发布",
    title: "We, Robot 与 Cybercab 叙事",
    sourceId: "tesla-we-robot-2024",
    context: "Tesla 官方活动摘录页面。",
    observation: "Cybercab、Optimus 与未来服务设想集中出现。",
    action: "可与财报问答、监管材料和后续实际服务资料继续对照。",
    outcome: "活动摘录不能替代完整视频或实际运营事实。",
    certainty: "结果待观察",
  },
  {
    id: "t-2025",
    year: "2025",
    type: "媒体追问",
    title: "Austin 上线前的公开追问",
    sourceId: "cnbc-faber-2025",
    context: "CNBC 对时间、范围和运营条件的公开采访。",
    observation: "外部媒体可把时间、范围和安全条件放回同一个连续问题组。",
    action: "与公司公告、服务页面和监管材料交叉核验。",
    outcome: "公开回答和运营结果仍需持续更新。",
    certainty: "结果待观察",
  },
];
